### ISSUE TITLE
Xelatex and tilde

### ISSUE THREAD

**Issue by seryrzu** [SPbSU-StatMod-Masters17/NE_MultidimDataAnalysis#4]
With current font for XeLaTeX.

If compile on Linux or Mac OS X:
\tilde and \widetilde do not appear in the pdf.

**Comment by Noxoomo** [comment]
ты почистить временные файлы после pdflatex не забыл? 
![screen shot 2015-11-18 at 20 04 00](https://cloud.githubusercontent.com/assets/2713489/11247990/c7427c84-8e2f-11e5-8020-cf559ba6e11f.png)

$\widetilde{a} caac \tilde{b}$

**Comment by seryrzu** [comment]
У меня мейк все чистит.

2015-11-18 20:06 GMT+03:00 Vasily notifications@github.com:

> ты почистить временные файлы после pdflatex не забыл?
> [image: screen shot 2015-11-18 at 20 04 00]
> https://cloud.githubusercontent.com/assets/2713489/11247990/c7427c84-8e2f-11e5-8020-cf559ba6e11f.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SPbSU-StatMod-Masters17/NE_MultidimDataAnalysis/issues/4#issuecomment-157780017
> .

## 

Best regards,
Andrew Bzikadze

**Comment by stacymiller** [comment]
@seryrzu мейк всё чистит только после удачной сборки.

**Comment by seryrzu** [comment]
Окей, я подправлю issue body. Имеется в виду, что сборка происходит, а тильды не отображаются.
То есть сборка то как раз "удачная"
