### ISSUE TITLE
47-48 не собирается в pdflatex

### ISSUE THREAD

**Issue by Noxoomo** [SPbSU-StatMod-Masters17/NE_MultidimDataAnalysis#7]
И этот символ тут точно должен быть?
![screenshot 2015-11-19 00 37 46](https://cloud.githubusercontent.com/assets/2713489/11255183/d87d3298-8e55-11e5-884d-cd9544803364.png)

**Comment by stacymiller** [comment]
Какой способ писать транспонирование наиболее корректен:
`\Tr{x}`
`x^\T`
`x^\mathrm T`
Второй не работает в pdflatex (будучи определён в pdflatex как `\DeclareMathOperator*{\T}{T}` — зачем это вообще?), первый рисует сомнительные вещи, третий слишком многословен.

**Comment by seryrzu** [comment]
Я третий пишу всегда, чтобы не было проблем несовместимости.
Каждый по-своему норовит...
Чт, 19 нояб. 2015 г. в 1:06, Anastasia Miller notifications@github.com:

**Comment by Noxoomo** [comment]
Который в \Tr{x} надо.  Вообще в гугле писали, что чаще всего используют как-раз тот символ, что там, а не всякие большие Т.

> Я третий пишу всегда, чтобы не было проблем несовместимости. 
> Каждый по-своему норовит… 

И поменять — тот еще квест. Берем первую команду, дальше уже подберем наиболее удачный и всех устраивающий стиль внутри нее

> Второй не работает в pdflatex (будучи определён в pdflatex как \DeclareMathOperator*{\T}{T}

Он вообще-то в  xelatex не работает, а в pdflatex как раз работал, кажется.

## 

Vasily Ershov

## 

Vasily Ershov

**Comment by Noxoomo** [comment]
С Лерой объединитесь, у нее тоже версия 47-48 билетов появилась
